### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 19972017n20132017n** [YoRyan/railsim-remote#1]
Hello, can you tell in a simplified way what needs to be done so that the indication and readings from the game go to the indication of the connected board? What files need to be added to the game, and what firmware should be inserted into the board?

**Comment by YoRyan** [comment]
Run the game, then run the server, then make GET/PUT requests with your HTTP client of choice. Where you go from there is up to you.

**Comment by 19972017n20132017n** [comment]
In general, should this be done for trainz 12?

**Comment by YoRyan** [comment]
This project is only compatible with Train Sim Classic/Train Simulator/RailWorks. I cannot help you with Trainz.
